In [1]:
import requests
from bs4 import BeautifulSoup
import urllib3
urllib3.disable_warnings()

In [2]:
url = "https://finance.naver.com/item/sise.naver?code=005930"

In [3]:
res = requests.get(url, verify = False)
res.raise_for_status()

In [4]:
soup = BeautifulSoup(res.text, "lxml")

In [42]:
stocks = soup.find_all("td", attrs = {"class": "num"})

In [48]:
price = stocks[4].span.get_text()
print(price)

				+0.52%

In [69]:
link = stocks[1].span["class"]
print(link)

['tah', 'p11']

In [70]:
print("https://finance.naver.com/" + str(link))

https://finance.naver.com/['tah', 'p11']

In [64]:
for stock in stocks :
    price = stocks[1].span.get_text()
    link = "https://finance.naver.com/" + str(stocks)
    print(price, link)

58,100 https://finance.naver.com/[<td class="num"><strong class="tah p11" id="_nowVal">58,100</strong></td>, <td class="num"><span class="tah p11">58,100</span></td>, <td class="num"><strong id="_diff">
<em class="bu_p bu_pup" style="margin:0 4px 0 0"><span class="blind">상승</span></em><span class="tah p11 red01">
				300
				</span>
</strong></td>, <td class="num"><span class="tah p11">58,000</span></td>, <td class="num"><strong id="_rate">
<span class="tah p11 red01">
				+0.52%
				</span>
</strong></td>, <td class="num"><span class="tah p11">57,800</span></td>, <td class="num"><span class="tah p11" id="_quant">5,931,319</span></td>, <td class="num"><span class="tah p11">58,200</span></td>, <td class="num"><span class="tah p11" id="_amount">


						345,987



				</span></td>, <td class="num"><span class="tah p11" id="_high">58,800</span></td>, <td class="num">
<span class="tah p11">100원</span>
</td>, <td class="num"><span class="tah p11" id="_low">57,900</span></td>, <td class="num"><span class="tah p11">75,100</span></td>, <td class="num"><span class="tah p11">72,000</span></td>, <td class="num"><span class="tah p11">40,500</span></td>, <td class="num"><span class="tah p11">38,800</span></td>, <td class="num"><span class="tah p11" id="_sise_per">


					9.43

				</span></td>, <td class="num"><span class="tah p11" id="_sise_eps">


					6,164

				</span></td>, <td class="num"><span class="tah p11">79,600</span></td>, <td align="left" class="num"><span class="tah p11">51,800</span></td>, <td class="num"><span class="p11"><span class="tah" id="_sise_market_sum">3,468,444</span>억원</span></td>, <td class="num"><span class="p11"><span class="tah">5,969,782,550</span></span></td>, <td class="num"><span class="p11"><span class="tah">2,974,041</span>천주</span></td>, <td class="num"><span class="p11"><span class="tah">778,046</span>백만</span></td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,875

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,500

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,196

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,400

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								64,159

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,300

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								79,789

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,200

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							198,502

					</strong></span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							58,100

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							58,000

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							166,568

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,900

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								260,525

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,800

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								241,810

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,700

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								264,655

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,600

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								175,538

						</span>
</td>, <td class="num bor" width="71"><strong class="tah p11 nv01">


						1,019,581

				</strong></td>]
58,100 https://finance.naver.com/[<td class="num"><strong class="tah p11" id="_nowVal">58,100</strong></td>, <td class="num"><span class="tah p11">58,100</span></td>, <td class="num"><strong id="_diff">
<em class="bu_p bu_pup" style="margin:0 4px 0 0"><span class="blind">상승</span></em><span class="tah p11 red01">
				300
				</span>
</strong></td>, <td class="num"><span class="tah p11">58,000</span></td>, <td class="num"><strong id="_rate">
<span class="tah p11 red01">
				+0.52%
				</span>
</strong></td>, <td class="num"><span class="tah p11">57,800</span></td>, <td class="num"><span class="tah p11" id="_quant">5,931,319</span></td>, <td class="num"><span class="tah p11">58,200</span></td>, <td class="num"><span class="tah p11" id="_amount">


						345,987



				</span></td>, <td class="num"><span class="tah p11" id="_high">58,800</span></td>, <td class="num">
<span class="tah p11">100원</span>
</td>, <td class="num"><span class="tah p11" id="_low">57,900</span></td>, <td class="num"><span class="tah p11">75,100</span></td>, <td class="num"><span class="tah p11">72,000</span></td>, <td class="num"><span class="tah p11">40,500</span></td>, <td class="num"><span class="tah p11">38,800</span></td>, <td class="num"><span class="tah p11" id="_sise_per">


					9.43

				</span></td>, <td class="num"><span class="tah p11" id="_sise_eps">


					6,164

				</span></td>, <td class="num"><span class="tah p11">79,600</span></td>, <td align="left" class="num"><span class="tah p11">51,800</span></td>, <td class="num"><span class="p11"><span class="tah" id="_sise_market_sum">3,468,444</span>억원</span></td>, <td class="num"><span class="p11"><span class="tah">5,969,782,550</span></span></td>, <td class="num"><span class="p11"><span class="tah">2,974,041</span>천주</span></td>, <td class="num"><span class="p11"><span class="tah">778,046</span>백만</span></td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,875

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,500

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,196

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,400

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								64,159

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,300

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								79,789

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,200

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							198,502

					</strong></span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							58,100

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							58,000

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							166,568

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,900

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								260,525

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,800

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								241,810

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,700

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								264,655

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,600

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								175,538

						</span>
</td>, <td class="num bor" width="71"><strong class="tah p11 nv01">


						1,019,581

				</strong></td>]
58,100 https://finance.naver.com/[<td class="num"><strong class="tah p11" id="_nowVal">58,100</strong></td>, <td class="num"><span class="tah p11">58,100</span></td>, <td class="num"><strong id="_diff">
<em class="bu_p bu_pup" style="margin:0 4px 0 0"><span class="blind">상승</span></em><span class="tah p11 red01">
				300
				</span>
</strong></td>, <td class="num"><span class="tah p11">58,000</span></td>, <td class="num"><strong id="_rate">
<span class="tah p11 red01">
				+0.52%
				</span>
</strong></td>, <td class="num"><span class="tah p11">57,800</span></td>, <td class="num"><span class="tah p11" id="_quant">5,931,319</span></td>, <td class="num"><span class="tah p11">58,200</span></td>, <td class="num"><span class="tah p11" id="_amount">


						345,987



				</span></td>, <td class="num"><span class="tah p11" id="_high">58,800</span></td>, <td class="num">
<span class="tah p11">100원</span>
</td>, <td class="num"><span class="tah p11" id="_low">57,900</span></td>, <td class="num"><span class="tah p11">75,100</span></td>, <td class="num"><span class="tah p11">72,000</span></td>, <td class="num"><span class="tah p11">40,500</span></td>, <td class="num"><span class="tah p11">38,800</span></td>, <td class="num"><span class="tah p11" id="_sise_per">


					9.43

				</span></td>, <td class="num"><span class="tah p11" id="_sise_eps">


					6,164

				</span></td>, <td class="num"><span class="tah p11">79,600</span></td>, <td align="left" class="num"><span class="tah p11">51,800</span></td>, <td class="num"><span class="p11"><span class="tah" id="_sise_market_sum">3,468,444</span>억원</span></td>, <td class="num"><span class="p11"><span class="tah">5,969,782,550</span></span></td>, <td class="num"><span class="p11"><span class="tah">2,974,041</span>천주</span></td>, <td class="num"><span class="p11"><span class="tah">778,046</span>백만</span></td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,875

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,500

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,196

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,400

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								64,159

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,300

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								79,789

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,200

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							198,502

					</strong></span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							58,100

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							58,000

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							166,568

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,900

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								260,525

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,800

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								241,810

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,700

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								264,655

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,600

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								175,538

						</span>
</td>, <td class="num bor" width="71"><strong class="tah p11 nv01">


						1,019,581

				</strong></td>]
58,100 https://finance.naver.com/[<td class="num"><strong class="tah p11" id="_nowVal">58,100</strong></td>, <td class="num"><span class="tah p11">58,100</span></td>, <td class="num"><strong id="_diff">
<em class="bu_p bu_pup" style="margin:0 4px 0 0"><span class="blind">상승</span></em><span class="tah p11 red01">
				300
				</span>
</strong></td>, <td class="num"><span class="tah p11">58,000</span></td>, <td class="num"><strong id="_rate">
<span class="tah p11 red01">
				+0.52%
				</span>
</strong></td>, <td class="num"><span class="tah p11">57,800</span></td>, <td class="num"><span class="tah p11" id="_quant">5,931,319</span></td>, <td class="num"><span class="tah p11">58,200</span></td>, <td class="num"><span class="tah p11" id="_amount">


						345,987



				</span></td>, <td class="num"><span class="tah p11" id="_high">58,800</span></td>, <td class="num">
<span class="tah p11">100원</span>
</td>, <td class="num"><span class="tah p11" id="_low">57,900</span></td>, <td class="num"><span class="tah p11">75,100</span></td>, <td class="num"><span class="tah p11">72,000</span></td>, <td class="num"><span class="tah p11">40,500</span></td>, <td class="num"><span class="tah p11">38,800</span></td>, <td class="num"><span class="tah p11" id="_sise_per">


					9.43

				</span></td>, <td class="num"><span class="tah p11" id="_sise_eps">


					6,164

				</span></td>, <td class="num"><span class="tah p11">79,600</span></td>, <td align="left" class="num"><span class="tah p11">51,800</span></td>, <td class="num"><span class="p11"><span class="tah" id="_sise_market_sum">3,468,444</span>억원</span></td>, <td class="num"><span class="p11"><span class="tah">5,969,782,550</span></span></td>, <td class="num"><span class="p11"><span class="tah">2,974,041</span>천주</span></td>, <td class="num"><span class="p11"><span class="tah">778,046</span>백만</span></td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,875

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,500

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,196

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,400

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								64,159

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,300

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								79,789

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,200

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							198,502

					</strong></span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							58,100

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							58,000

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							166,568

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,900

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								260,525

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,800

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								241,810

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,700

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								264,655

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,600

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								175,538

						</span>
</td>, <td class="num bor" width="71"><strong class="tah p11 nv01">


						1,019,581

				</strong></td>]
58,100 https://finance.naver.com/[<td class="num"><strong class="tah p11" id="_nowVal">58,100</strong></td>, <td class="num"><span class="tah p11">58,100</span></td>, <td class="num"><strong id="_diff">
<em class="bu_p bu_pup" style="margin:0 4px 0 0"><span class="blind">상승</span></em><span class="tah p11 red01">
				300
				</span>
</strong></td>, <td class="num"><span class="tah p11">58,000</span></td>, <td class="num"><strong id="_rate">
<span class="tah p11 red01">
				+0.52%
				</span>
</strong></td>, <td class="num"><span class="tah p11">57,800</span></td>, <td class="num"><span class="tah p11" id="_quant">5,931,319</span></td>, <td class="num"><span class="tah p11">58,200</span></td>, <td class="num"><span class="tah p11" id="_amount">


						345,987



				</span></td>, <td class="num"><span class="tah p11" id="_high">58,800</span></td>, <td class="num">
<span class="tah p11">100원</span>
</td>, <td class="num"><span class="tah p11" id="_low">57,900</span></td>, <td class="num"><span class="tah p11">75,100</span></td>, <td class="num"><span class="tah p11">72,000</span></td>, <td class="num"><span class="tah p11">40,500</span></td>, <td class="num"><span class="tah p11">38,800</span></td>, <td class="num"><span class="tah p11" id="_sise_per">


					9.43

				</span></td>, <td class="num"><span class="tah p11" id="_sise_eps">


					6,164

				</span></td>, <td class="num"><span class="tah p11">79,600</span></td>, <td align="left" class="num"><span class="tah p11">51,800</span></td>, <td class="num"><span class="p11"><span class="tah" id="_sise_market_sum">3,468,444</span>억원</span></td>, <td class="num"><span class="p11"><span class="tah">5,969,782,550</span></span></td>, <td class="num"><span class="p11"><span class="tah">2,974,041</span>천주</span></td>, <td class="num"><span class="p11"><span class="tah">778,046</span>백만</span></td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,875

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,500

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								98,196

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,400

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								64,159

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,300

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								79,789

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01">


								58,200

						</span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							198,502

					</strong></span>
</td>, <td class="num bg01">
<span class="tah p11 nv01"><strong>


							58,100

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							58,000

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01"><strong>


							166,568

					</strong></span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,900

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								260,525

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,800

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								241,810

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,700

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								264,655

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								57,600

						</span>
</td>, <td class="num bg02">
<span class="tah p11 red01">


								175,538

						</span>
</td>, <td class="num bor" width="71"><strong class="tah p11 nv01">


						1,019,581

				</strong></td>]
58,100 https://finance.naver.com/[<td class="num"><strong class="tah p11" id="_nowVal">58,100</strong></td>, <td class="num"><span class="tah p11">58,100</span></td>, <td class="num"><strong id="_diff">
<em class="bu_p bu_pup" style="margin:0 4px 0 0"><span class="blind">상승</span></em><span class="tah p11 red01">
				300
				</span>
</strong></td>, <td class="num"><span class="tah p11">58,000</span></td>, <td class="num"><strong id="_rate">
<span class="tah p11 red01">
				+0.52%
				</span>
</strong></td>, <td class="num"><span class="tah p11">57,800</span></td>, <td class="num"><span class="tah p11" id="_quant">5,931,319</span></td>, <td class="num"><span class="tah p11">58,200</span></td>, <td class="num"><span class="tah p11" id="_amount">


						345,987


